### ISSUE TITLE
Variable "i" [Line: 27] is not defined in index.js 

### ISSUE THREAD

**Issue by theYasirRehman** [moov2/npm-msdeploy#2]
Variable "i" is not defined [Line: 27] is not defined in the index.js file. It causes "ReferenceError: i is not defined" error on running npm run deploy command.

![image](https://user-images.githubusercontent.com/51193361/60975297-304e0080-a345-11e9-9aca-05868d595eb8.png)
![image](https://user-images.githubusercontent.com/51193361/60975430-6e4b2480-a345-11e9-9aa8-e3916179239f.png)

**Comment by mobinzk** [comment]
@YasiRehman Thanks for reporting this issue, we'll have a fix for this by end of this week.
